version: '3.8'

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"

  web:
    build: .
    depends_on:
      - redis
    environment:
      FLASK_APP: wsgi.py
      FLASK_ENV: production
      DATABASE_URL: sqlite:////app/instance/arweave_tracker.db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      REDIS_URL: redis://redis:6379/2
      SECRET_KEY: bodhi
    volumes:
      - ./:/app
      - ./logs:/var/log/hunter-web
    ports:
      - "8000:8000"

  worker:
    build: .
    depends_on:
      - redis
    command: ["celery", "-A", "celery_worker_entrypoint.celery_app", "worker", "--loglevel=INFO"]
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DATABASE_URL: sqlite:////app/instance/arweave_tracker.db
      SECRET_KEY: bodhi
    volumes:
      - ./instance:/app/instance

  beat:
    build: .
    depends_on:
      - redis
    command: ["celery", "-A", "celery_worker_entrypoint.celery_app", "beat", "--loglevel=INFO"]
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DATABASE_URL: sqlite:////app/instance/arweave_tracker.db
      SECRET_KEY: your-very-secret-key-change-this
    volumes:
      - ./instance:/app/instance