version: "3.8"

services:
  web:
    build: .
    env_file: .env
    working_dir: /app
    command:
      - gunicorn
      - "celery_worker_entrypoint:app"
      - "--bind"
      - "0.0.0.0:8000"
      - "--workers"
      - "4"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./user_files:/app/uploads
    depends_on:
      - redis

  worker_crypto:
    build: .
    env_file: .env
    working_dir: /app
    command:
      - celery
      - "-A"
      - "celery_worker_entrypoint:celery_app"
      - worker
      - "-Q"
      - "crypto_main,crypto_priority,ethereum,cipher,hash_crack"
      - "--concurrency=4"
      - "--loglevel=info"
    volumes:
      - ./:/app
      - ./user_files:/app/uploads
    depends_on:
      - redis

  worker_llm:
    build: .
    env_file: .env
    working_dir: /app
    command:
      - celery
      - "-A"
      - "celery_worker_entrypoint:celery_app"
      - worker
      - "-Q"
      - "llm_analysis,llm_priority"
      - "--concurrency=2"
      - "--loglevel=info"
    volumes:
      - ./:/app
      - ./user_files:/app/uploads
    depends_on:
      - redis

  scheduler:
    build: .
    env_file: .env
    working_dir: /app
    command:
      - celery
      - "-A"
      - "celery_worker_entrypoint:celery_app"
      - beat
      - "--loglevel=info"
    volumes:
      - ./:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
