services:
  web:
    env_file:
      - .env
    build: .
    command: gunicorn wsgi:app --bind 0.0.0.0:5000


  worker:
    env_file:
      - .env
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info

