version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:////app/instance/arweave_tracker.db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-no-rebuilds-needed
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app  # MOUNT SOURCE CODE - NO MORE REBUILDS!
      - ./instance:/app/instance
    depends_on:
      - redis
    stdin_open: true
    tty: true
    command: python -m flask run --host=0.0.0.0 --port=8000 --reload
