version: '3.8'
# Development configuration override
services:
  web:
    build:
      target: development
    command: flask run --host=0.0.0.0 --port=8000
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    volumes:
      - ..:/app
    ports:
      - "8000:8000"

  worker:
    build:
      target: development
    command: celery -A crypto_hunter_web.services.celery_app worker --loglevel=info --concurrency=2
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    volumes:
      - ..:/app

  beat:
    build:
      target: development
    command: celery -A crypto_hunter_web.services.celery_app beat --loglevel=info
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    volumes:
      - ..:/app

  flower:
    build:
      target: development
    command: celery -A crypto_hunter_web.services.celery_app flower --port=5555 --basic_auth=${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-admin123}
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    volumes:
      - ..:/app
